# Generated by Django 4.0.8 on 2023-02-08 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_userproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='shopping_cart.userproxy'),
        ),
    ]
