# Generated by Django 4.0.8 on 2023-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_userproxy_created_at_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproxy',
            old_name='user',
            new_name='user_id',
        ),
    ]
