# Generated by Django 4.0.8 on 2023-02-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0006_rename_user_userproxy_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproxy',
            old_name='user_id',
            new_name='user',
        ),
    ]
