# Generated by Django 4.0.8 on 2023-02-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_rename_user_id_userproxy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproxy',
            name='cookie',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
