# Generated by Django 4.0.8 on 2023-02-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
