# Generated by Django 4.0.8 on 2023-02-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_cart', '0008_alter_userproxy_cookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='shopping_cart.userproxy')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NO', 'Not Ordered'), ('PR', 'Deliver in Process'), ('DL', 'Delivered')], default='NO', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.address')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.cart')),
            ],
        ),
    ]
