# Generated by Django 4.0.8 on 2023-02-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email',
            new_name='cookie_email',
        ),
    ]
